services:
  iiot-dashboard:
    build: .
    image: iiot-dashboard:latest
    container_name: iiot-dashboard
    ports:
      - "8000:8000"
      - "8888:8888"
      - "8554:8554"
      - "9997:9997"
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
